import { ProductListItem } from "@/entities/product/model/types";

const IMG = {
  white:
    "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=600&h=600&fit=crop&auto=format",
  red: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&h=600&fit=crop&auto=format",
  black:
    "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&h=600&fit=crop&auto=format",
  blue: "https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=600&h=600&fit=crop&auto=format",
  green:
    "https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&h=600&fit=crop&auto=format",
  grey: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&h=600&fit=crop&auto=format",
  tan: "https://images.unsplash.com/photo-1584735175315-9d5df23860e6?w=600&h=600&fit=crop&auto=format",
} as const;

export const mockProductsDb: ProductListItem[] = [
  {
    id: "prod-1",
    model: "Air Zoom Pegasus 41",
    brand: "Nike",
    basePrice: 139.99,
    variantsCount: 3,
    variants: [
      { variantId: "prod-1-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-1-black", colorName: "Black", imageUrl: IMG.black },
      { variantId: "prod-1-blue", colorName: "Blue", imageUrl: IMG.blue },
    ],
  },
  {
    id: "prod-2",
    model: "Ultraboost Light",
    brand: "Adidas",
    basePrice: 189.99,
    variantsCount: 5,
    variants: [
      { variantId: "prod-2-black", colorName: "Black", imageUrl: IMG.black },
      { variantId: "prod-2-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-2-grey", colorName: "Grey", imageUrl: IMG.grey },
      { variantId: "prod-2-red", colorName: "Red", imageUrl: IMG.red },
    ],
  },
  {
    id: "prod-3",
    model: "574 Core",
    brand: "New Balance",
    basePrice: 99.99,
    variantsCount: 2,
    variants: [
      { variantId: "prod-3-grey", colorName: "Grey", imageUrl: IMG.grey },
      { variantId: "prod-3-tan", colorName: "Tan", imageUrl: IMG.tan },
    ],
  },
  {
    id: "prod-4",
    model: "Air Force 1 '07",
    brand: "Nike",
    basePrice: 114.99,
    variantsCount: 4,
    variants: [
      { variantId: "prod-4-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-4-black", colorName: "Black", imageUrl: IMG.black },
      { variantId: "prod-4-green", colorName: "Green", imageUrl: IMG.green },
      { variantId: "prod-4-red", colorName: "Red", imageUrl: IMG.red },
    ],
  },
  {
    id: "prod-5",
    model: "Samba OG",
    brand: "Adidas",
    basePrice: 99.99,
    variantsCount: 3,
    variants: [
      { variantId: "prod-5-black", colorName: "Black", imageUrl: IMG.black },
      { variantId: "prod-5-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-5-tan", colorName: "Tan", imageUrl: IMG.tan },
    ],
  },
  {
    id: "prod-6",
    model: "990v6 Core",
    brand: "New Balance",
    basePrice: 199.99,
    variantsCount: 2,
    variants: [
      { variantId: "prod-6-grey", colorName: "Grey", imageUrl: IMG.grey },
      { variantId: "prod-6-black", colorName: "Black", imageUrl: IMG.black },
    ],
  },
  {
    id: "prod-7",
    model: "Suede Classic",
    brand: "Puma",
    basePrice: 74.99,
    variantsCount: 6,
    variants: [
      { variantId: "prod-7-red", colorName: "Red", imageUrl: IMG.red },
      { variantId: "prod-7-blue", colorName: "Blue", imageUrl: IMG.blue },
      { variantId: "prod-7-green", colorName: "Green", imageUrl: IMG.green },
      { variantId: "prod-7-black", colorName: "Black", imageUrl: IMG.black },
    ],
  },
  {
    id: "prod-8",
    model: "Gel-Kayano 14",
    brand: "Asics",
    basePrice: 149.99,
    variantsCount: 4,
    variants: [
      { variantId: "prod-8-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-8-grey", colorName: "Grey", imageUrl: IMG.grey },
      { variantId: "prod-8-blue", colorName: "Blue", imageUrl: IMG.blue },
      { variantId: "prod-8-black", colorName: "Black", imageUrl: IMG.black },
    ],
  },
  {
    id: "prod-9",
    model: "Club C 85 Vintage",
    brand: "Reebok",
    basePrice: 84.99,
    variantsCount: 3,
    variants: [
      { variantId: "prod-9-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-9-green", colorName: "Green", imageUrl: IMG.green },
      { variantId: "prod-9-tan", colorName: "Tan", imageUrl: IMG.tan },
    ],
  },
  {
    id: "prod-10",
    model: "Air Jordan 1 Retro High",
    brand: "Nike",
    basePrice: 179.99,
    variantsCount: 1,
    variants: [
      { variantId: "prod-10-red", colorName: "Red", imageUrl: IMG.red },
    ],
  },
  {
    id: "prod-11",
    model: "Stan Smith",
    brand: "Adidas",
    basePrice: 104.99,
    variantsCount: 8,
    variants: [
      { variantId: "prod-11-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-11-green", colorName: "Green", imageUrl: IMG.green },
      { variantId: "prod-11-blue", colorName: "Blue", imageUrl: IMG.blue },
      { variantId: "prod-11-black", colorName: "Black", imageUrl: IMG.black },
    ],
  },
  {
    id: "prod-12",
    model: "2002R",
    brand: "New Balance",
    basePrice: 139.99,
    variantsCount: 4,
    variants: [
      { variantId: "prod-12-grey", colorName: "Grey", imageUrl: IMG.grey },
      { variantId: "prod-12-black", colorName: "Black", imageUrl: IMG.black },
      { variantId: "prod-12-tan", colorName: "Tan", imageUrl: IMG.tan },
      { variantId: "prod-12-blue", colorName: "Blue", imageUrl: IMG.blue },
    ],
  },
  {
    id: "prod-13",
    model: "RS-X3",
    brand: "Puma",
    basePrice: 109.99,
    variantsCount: 2,
    variants: [
      { variantId: "prod-13-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-13-red", colorName: "Red", imageUrl: IMG.red },
    ],
  },
  {
    id: "prod-14",
    model: "Gel-Lyte III",
    brand: "Asics",
    basePrice: 129.99,
    variantsCount: 5,
    variants: [
      { variantId: "prod-14-blue", colorName: "Blue", imageUrl: IMG.blue },
      { variantId: "prod-14-grey", colorName: "Grey", imageUrl: IMG.grey },
      { variantId: "prod-14-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-14-green", colorName: "Green", imageUrl: IMG.green },
    ],
  },
  {
    id: "prod-15",
    model: "Classic Leather",
    brand: "Reebok",
    basePrice: 79.99,
    variantsCount: 3,
    variants: [
      { variantId: "prod-15-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-15-black", colorName: "Black", imageUrl: IMG.black },
      { variantId: "prod-15-grey", colorName: "Grey", imageUrl: IMG.grey },
    ],
  },
  {
    id: "prod-16",
    model: "Dunk Low",
    brand: "Nike",
    basePrice: 109.99,
    variantsCount: 7,
    variants: [
      { variantId: "prod-16-red", colorName: "Red", imageUrl: IMG.red },
      { variantId: "prod-16-green", colorName: "Green", imageUrl: IMG.green },
      { variantId: "prod-16-blue", colorName: "Blue", imageUrl: IMG.blue },
      { variantId: "prod-16-black", colorName: "Black", imageUrl: IMG.black },
    ],
  },
  {
    id: "prod-17",
    model: "Gazelle",
    brand: "Adidas",
    basePrice: 99.99,
    variantsCount: 6,
    variants: [
      { variantId: "prod-17-blue", colorName: "Blue", imageUrl: IMG.blue },
      { variantId: "prod-17-red", colorName: "Red", imageUrl: IMG.red },
      { variantId: "prod-17-green", colorName: "Green", imageUrl: IMG.green },
      { variantId: "prod-17-black", colorName: "Black", imageUrl: IMG.black },
    ],
  },
  {
    id: "prod-18",
    model: "550",
    brand: "New Balance",
    basePrice: 109.99,
    variantsCount: 4,
    variants: [
      { variantId: "prod-18-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-18-green", colorName: "Green", imageUrl: IMG.green },
      { variantId: "prod-18-grey", colorName: "Grey", imageUrl: IMG.grey },
      { variantId: "prod-18-red", colorName: "Red", imageUrl: IMG.red },
    ],
  },
  {
    id: "prod-19",
    model: "Mayze",
    brand: "Puma",
    basePrice: 89.99,
    variantsCount: 2,
    variants: [
      { variantId: "prod-19-black", colorName: "Black", imageUrl: IMG.black },
      { variantId: "prod-19-white", colorName: "White", imageUrl: IMG.white },
    ],
  },
  {
    id: "prod-20",
    model: "Air Max 90",
    brand: "Nike",
    basePrice: 129.99,
    variantsCount: 5,
    variants: [
      { variantId: "prod-20-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-20-grey", colorName: "Grey", imageUrl: IMG.grey },
      { variantId: "prod-20-red", colorName: "Red", imageUrl: IMG.red },
      { variantId: "prod-20-blue", colorName: "Blue", imageUrl: IMG.blue },
    ],
  },
  {
    id: "prod-21",
    model: "NMD_R1",
    brand: "Adidas",
    basePrice: 149.99,
    variantsCount: 3,
    variants: [
      { variantId: "prod-21-black", colorName: "Black", imageUrl: IMG.black },
      { variantId: "prod-21-grey", colorName: "Grey", imageUrl: IMG.grey },
      { variantId: "prod-21-blue", colorName: "Blue", imageUrl: IMG.blue },
    ],
  },
  {
    id: "prod-22",
    model: "XT-6",
    brand: "Salomon",
    basePrice: 199.99,
    variantsCount: 2,
    variants: [
      { variantId: "prod-22-black", colorName: "Black", imageUrl: IMG.black },
      { variantId: "prod-22-tan", colorName: "Tan", imageUrl: IMG.tan },
    ],
  },
  {
    id: "prod-23",
    model: "Clifton 9",
    brand: "Hoka",
    basePrice: 144.99,
    variantsCount: 4,
    variants: [
      { variantId: "prod-23-blue", colorName: "Blue", imageUrl: IMG.blue },
      { variantId: "prod-23-white", colorName: "White", imageUrl: IMG.white },
      { variantId: "prod-23-green", colorName: "Green", imageUrl: IMG.green },
      { variantId: "prod-23-grey", colorName: "Grey", imageUrl: IMG.grey },
    ],
  },
];
